#!/bin/bash

ECRECOVERPRECALC=${ECRECOVERPRECALC:-false}
jq --argjson key_value ${ECRECOVERPRECALC} '.["ECRecoverPrecalc"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
ECRECOVERPRECALCNTHREADS=${ECRECOVERPRECALCNTHREADS:-4}
jq --argjson key_value ${ECRECOVERPRECALCNTHREADS} '.["ECRecoverPrecalcNThreads"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
AGGREGATORCLIENTHOST=${AGGREGATORCLIENTHOST:-'13.229.74.5'}
jq --arg key_value "${AGGREGATORCLIENTHOST}" '.["aggregatorClientHost"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
AGGREGATORCLIENTMOCKTIMEOUT=${AGGREGATORCLIENTMOCKTIMEOUT:-10000000}
jq --argjson key_value ${AGGREGATORCLIENTMOCKTIMEOUT} '.["aggregatorClientMockTimeout"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
AGGREGATORCLIENTPORT=${AGGREGATORCLIENTPORT:-50081}
jq --argjson key_value ${AGGREGATORCLIENTPORT} '.["aggregatorClientPort"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
AGGREGATORCLIENTWATCHDOGTIMEOUT=${AGGREGATORCLIENTWATCHDOGTIMEOUT:-60000000}
jq --argjson key_value ${AGGREGATORCLIENTWATCHDOGTIMEOUT} '.["aggregatorClientWatchdogTimeout"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
AGGREGATORSERVERPORT=${AGGREGATORSERVERPORT:-50081}
jq --argjson key_value ${AGGREGATORSERVERPORT} '.["aggregatorServerPort"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
C12ACMPOLS=${C12ACMPOLS:-'runtime/c12a.commit'}
jq --arg key_value "${C12ACMPOLS}" '.["c12aCmPols"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
CLEANERPOLLINGPERIOD=${CLEANERPOLLINGPERIOD:-600}
jq --argjson key_value ${CLEANERPOLLINGPERIOD} '.["cleanerPollingPeriod"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
CONFIGPATH=${CONFIGPATH:-'config'}
jq --arg key_value "${CONFIGPATH}" '.["configPath"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
DATABASEURL=${DATABASEURL:-'postgresql://readonly_user:readonly_pass@13.229.74.5:5432/prover_db'}
jq --arg key_value "${DATABASEURL}" '.["databaseURL"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
DATABASEURL_DISABLED=${DATABASEURL_DISABLED:-'postgresql://statedb:statedb@127.0.0.1:5432/testdb'}
jq --arg key_value "${DATABASEURL_DISABLED}" '.["databaseURL_disabled"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
DBCACHESYNCHURL_DISABLED=${DBCACHESYNCHURL_DISABLED:-'127.0.0.1:50061'}
jq --arg key_value "${DBCACHESYNCHURL_DISABLED}" '.["dbCacheSynchURL_disabled"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
DBFLUSHINPARALLEL=${DBFLUSHINPARALLEL:-false}
jq --argjson key_value ${DBFLUSHINPARALLEL} '.["dbFlushInParallel"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
DBGETTREE=${DBGETTREE:-true}
jq --argjson key_value ${DBGETTREE} '.["dbGetTree"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
DBMTCACHESIZE=${DBMTCACHESIZE:-16384}
jq --argjson key_value ${DBMTCACHESIZE} '.["dbMTCacheSize"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
DBMULTIWRITE=${DBMULTIWRITE:-false}
jq --argjson key_value ${DBMULTIWRITE} '.["dbMultiWrite"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
DBNODESTABLENAME=${DBNODESTABLENAME:-'state.nodes'}
jq --arg key_value "${DBNODESTABLENAME}" '.["dbNodesTableName"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
DBNUMBEROFPOOLCONNECTIONS=${DBNUMBEROFPOOLCONNECTIONS:-30}
jq --argjson key_value ${DBNUMBEROFPOOLCONNECTIONS} '.["dbNumberOfPoolConnections"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
DBPROGRAMCACHESIZE=${DBPROGRAMCACHESIZE:-16384}
jq --argjson key_value ${DBPROGRAMCACHESIZE} '.["dbProgramCacheSize"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
DBPROGRAMTABLENAME=${DBPROGRAMTABLENAME:-'state.program'}
jq --arg key_value "${DBPROGRAMTABLENAME}" '.["dbProgramTableName"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
DBREADONLY=${DBREADONLY:-true}
jq --argjson key_value ${DBREADONLY} '.["dbReadOnly"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
EXECUTEINPARALLEL=${EXECUTEINPARALLEL:-true}
jq --argjson key_value ${EXECUTEINPARALLEL} '.["executeInParallel"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
EXECUTORCLIENTHOST=${EXECUTORCLIENTHOST:-'127.0.0.1'}
jq --arg key_value "${EXECUTORCLIENTHOST}" '.["executorClientHost"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
EXECUTORCLIENTLOOPS=${EXECUTORCLIENTLOOPS:-1}
jq --argjson key_value ${EXECUTORCLIENTLOOPS} '.["executorClientLoops"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
EXECUTORCLIENTPORT=${EXECUTORCLIENTPORT:-50071}
jq --argjson key_value ${EXECUTORCLIENTPORT} '.["executorClientPort"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
EXECUTORROMLINETRACES=${EXECUTORROMLINETRACES:-false}
jq --argjson key_value ${EXECUTORROMLINETRACES} '.["executorROMLineTraces"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
EXECUTORSERVERPORT=${EXECUTORSERVERPORT:-50071}
jq --argjson key_value ${EXECUTORSERVERPORT} '.["executorServerPort"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
EXECUTORTIMESTATISTICS=${EXECUTORTIMESTATISTICS:-false}
jq --argjson key_value ${EXECUTORTIMESTATISTICS} '.["executorTimeStatistics"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
FINALCMPOLS_DISABLED=${FINALCMPOLS_DISABLED:-'runtime/final.commit'}
jq --arg key_value "${FINALCMPOLS_DISABLED}" '.["finalCmPols_disabled"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
HASHDBSERVERPORT=${HASHDBSERVERPORT:-50061}
jq --argjson key_value ${HASHDBSERVERPORT} '.["hashDBServerPort"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
HASHDBURL=${HASHDBURL:-'local'}
jq --arg key_value "${HASHDBURL}" '.["hashDBURL"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
INPUTFILE=${INPUTFILE:-'testvectors/aggregatedProof/recursive1.zkin.proof_0.json'}
jq --arg key_value "${INPUTFILE}" '.["inputFile"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
INPUTFILE2=${INPUTFILE2:-'testvectors/aggregatedProof/recursive1.zkin.proof_1.json'}
jq --arg key_value "${INPUTFILE2}" '.["inputFile2"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
LOADDBTOMEMCACHE=${LOADDBTOMEMCACHE:-true}
jq --argjson key_value ${LOADDBTOMEMCACHE} '.["loadDBToMemCache"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
LOADDBTOMEMCACHEINPARALLEL=${LOADDBTOMEMCACHEINPARALLEL:-false}
jq --argjson key_value ${LOADDBTOMEMCACHEINPARALLEL} '.["loadDBToMemCacheInParallel"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
LOADDBTOMEMTIMEOUT=${LOADDBTOMEMTIMEOUT:-30000000}
jq --argjson key_value ${LOADDBTOMEMTIMEOUT} '.["loadDBToMemTimeout"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
LOGEXECUTORSERVERINPUT=${LOGEXECUTORSERVERINPUT:-false}
jq --argjson key_value ${LOGEXECUTORSERVERINPUT} '.["logExecutorServerInput"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
LOGEXECUTORSERVERINPUTGASTHRESHOLD=${LOGEXECUTORSERVERINPUTGASTHRESHOLD:-0}
jq --argjson key_value ${LOGEXECUTORSERVERINPUTGASTHRESHOLD} '.["logExecutorServerInputGasThreshold"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
LOGEXECUTORSERVERRESPONSES=${LOGEXECUTORSERVERRESPONSES:-false}
jq --argjson key_value ${LOGEXECUTORSERVERRESPONSES} '.["logExecutorServerResponses"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
LOGEXECUTORSERVERTXS=${LOGEXECUTORSERVERTXS:-true}
jq --argjson key_value ${LOGEXECUTORSERVERTXS} '.["logExecutorServerTxs"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
LOGREMOTEDBREADS=${LOGREMOTEDBREADS:-false}
jq --argjson key_value ${LOGREMOTEDBREADS} '.["logRemoteDbReads"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
MAPCONSTPOLSFILE=${MAPCONSTPOLSFILE:-false}
jq --argjson key_value ${MAPCONSTPOLSFILE} '.["mapConstPolsFile"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
MAPCONSTANTSTREEFILE=${MAPCONSTANTSTREEFILE:-false}
jq --argjson key_value ${MAPCONSTANTSTREEFILE} '.["mapConstantsTreeFile"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
MAXEXECUTORTHREADS=${MAXEXECUTORTHREADS:-20}
jq --argjson key_value ${MAXEXECUTORTHREADS} '.["maxExecutorThreads"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
MAXHASHDBTHREADS=${MAXHASHDBTHREADS:-8}
jq --argjson key_value ${MAXHASHDBTHREADS} '.["maxHashDBThreads"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
MAXPROVERTHREADS=${MAXPROVERTHREADS:-8}
jq --argjson key_value ${MAXPROVERTHREADS} '.["maxProverThreads"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
OPCODETRACER=${OPCODETRACER:-false}
jq --argjson key_value ${OPCODETRACER} '.["opcodeTracer"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
OUTPUTPATH=${OUTPUTPATH:-'runtime/output'}
jq --arg key_value "${OUTPUTPATH}" '.["outputPath"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
PROOFFILE=${PROOFFILE:-'proof.json'}
jq --arg key_value "${PROOFFILE}" '.["proofFile"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
PROVERNAME=${PROVERNAME:-'readonly-prover'}
jq --arg key_value "${PROVERNAME}" '.["proverName"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
PUBLICSOUTPUT=${PUBLICSOUTPUT:-'public.json'}
jq --arg key_value "${PUBLICSOUTPUT}" '.["publicsOutput"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RECURSIVE1CMPOLS_DISABLED=${RECURSIVE1CMPOLS_DISABLED:-'runtime/recursive1.commit'}
jq --arg key_value "${RECURSIVE1CMPOLS_DISABLED}" '.["recursive1CmPols_disabled"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RECURSIVE2CMPOLS_DISABLED=${RECURSIVE2CMPOLS_DISABLED:-'runtime/recursive2.commit'}
jq --arg key_value "${RECURSIVE2CMPOLS_DISABLED}" '.["recursive2CmPols_disabled"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RECURSIVEFCMPOLS_DISABLED=${RECURSIVEFCMPOLS_DISABLED:-'runtime/recursivef.commit'}
jq --arg key_value "${RECURSIVEFCMPOLS_DISABLED}" '.["recursivefCmPols_disabled"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
REQUESTSPERSISTENCE=${REQUESTSPERSISTENCE:-3600}
jq --argjson key_value ${REQUESTSPERSISTENCE} '.["requestsPersistence"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNAGGREGATORCLIENT=${RUNAGGREGATORCLIENT:-true}
jq --argjson key_value ${RUNAGGREGATORCLIENT} '.["runAggregatorClient"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNAGGREGATORCLIENTMOCK=${RUNAGGREGATORCLIENTMOCK:-false}
jq --argjson key_value ${RUNAGGREGATORCLIENTMOCK} '.["runAggregatorClientMock"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNAGGREGATORSERVER=${RUNAGGREGATORSERVER:-false}
jq --argjson key_value ${RUNAGGREGATORSERVER} '.["runAggregatorServer"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNBINARYSMTEST=${RUNBINARYSMTEST:-false}
jq --argjson key_value ${RUNBINARYSMTEST} '.["runBinarySMTest"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNBLAKETEST=${RUNBLAKETEST:-false}
jq --argjson key_value ${RUNBLAKETEST} '.["runBlakeTest"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNECRECOVERTEST=${RUNECRECOVERTEST:-false}
jq --argjson key_value ${RUNECRECOVERTEST} '.["runECRecoverTest"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNEXECUTORCLIENT=${RUNEXECUTORCLIENT:-false}
jq --argjson key_value ${RUNEXECUTORCLIENT} '.["runExecutorClient"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNEXECUTORCLIENTMULTITHREAD=${RUNEXECUTORCLIENTMULTITHREAD:-false}
jq --argjson key_value ${RUNEXECUTORCLIENTMULTITHREAD} '.["runExecutorClientMultithread"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNEXECUTORSERVER=${RUNEXECUTORSERVER:-false}
jq --argjson key_value ${RUNEXECUTORSERVER} '.["runExecutorServer"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNFILEEXECUTOR=${RUNFILEEXECUTOR:-false}
jq --argjson key_value ${RUNFILEEXECUTOR} '.["runFileExecutor"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNFILEGENAGGREGATEDPROOF=${RUNFILEGENAGGREGATEDPROOF:-false}
jq --argjson key_value ${RUNFILEGENAGGREGATEDPROOF} '.["runFileGenAggregatedProof"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNFILEGENBATCHPROOF=${RUNFILEGENBATCHPROOF:-false}
jq --argjson key_value ${RUNFILEGENBATCHPROOF} '.["runFileGenBatchProof"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNFILEGENFINALPROOF=${RUNFILEGENFINALPROOF:-false}
jq --argjson key_value ${RUNFILEGENFINALPROOF} '.["runFileGenFinalProof"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNFILEPROCESSBATCH=${RUNFILEPROCESSBATCH:-false}
jq --argjson key_value ${RUNFILEPROCESSBATCH} '.["runFileProcessBatch"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNFILEPROCESSBATCHMULTITHREAD=${RUNFILEPROCESSBATCHMULTITHREAD:-false}
jq --argjson key_value ${RUNFILEPROCESSBATCHMULTITHREAD} '.["runFileProcessBatchMultithread"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNHASHDBSERVER=${RUNHASHDBSERVER:-false}
jq --argjson key_value ${RUNHASHDBSERVER} '.["runHashDBServer"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNHASHDBTEST=${RUNHASHDBTEST:-false}
jq --argjson key_value ${RUNHASHDBTEST} '.["runHashDBTest"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNKECCAKSCRIPTGENERATOR=${RUNKECCAKSCRIPTGENERATOR:-false}
jq --argjson key_value ${RUNKECCAKSCRIPTGENERATOR} '.["runKeccakScriptGenerator"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNKECCAKTEST=${RUNKECCAKTEST:-false}
jq --argjson key_value ${RUNKECCAKTEST} '.["runKeccakTest"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNMEMALIGNSMTEST=${RUNMEMALIGNSMTEST:-false}
jq --argjson key_value ${RUNMEMALIGNSMTEST} '.["runMemAlignSMTest"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNSHA256TEST=${RUNSHA256TEST:-false}
jq --argjson key_value ${RUNSHA256TEST} '.["runSHA256Test"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
RUNSTORAGESMTEST=${RUNSTORAGESMTEST:-false}
jq --argjson key_value ${RUNSTORAGESMTEST} '.["runStorageSMTest"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
SAVEDBREADSTOFILE=${SAVEDBREADSTOFILE:-true}
jq --argjson key_value ${SAVEDBREADSTOFILE} '.["saveDbReadsToFile"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
SAVEDBREADSTOFILEONCHANGE=${SAVEDBREADSTOFILEONCHANGE:-false}
jq --argjson key_value ${SAVEDBREADSTOFILEONCHANGE} '.["saveDbReadsToFileOnChange"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
SAVEFILESINSUBFOLDERS=${SAVEFILESINSUBFOLDERS:-false}
jq --argjson key_value ${SAVEFILESINSUBFOLDERS} '.["saveFilesInSubfolders"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
SAVEINPUTTOFILE=${SAVEINPUTTOFILE:-false}
jq --argjson key_value ${SAVEINPUTTOFILE} '.["saveInputToFile"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
SAVEOUTPUTTOFILE=${SAVEOUTPUTTOFILE:-true}
jq --argjson key_value ${SAVEOUTPUTTOFILE} '.["saveOutputToFile"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
SAVEPROOFTOFILE=${SAVEPROOFTOFILE:-true}
jq --argjson key_value ${SAVEPROOFTOFILE} '.["saveProofToFile"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
SAVEREQUESTTOFILE=${SAVEREQUESTTOFILE:-true}
jq --argjson key_value ${SAVEREQUESTTOFILE} '.["saveRequestToFile"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
SAVERESPONSETOFILE=${SAVERESPONSETOFILE:-true}
jq --argjson key_value ${SAVERESPONSETOFILE} '.["saveResponseToFile"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
STATEMANAGER=${STATEMANAGER:-false}
jq --argjson key_value ${STATEMANAGER} '.["stateManager"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
USEASSOCIATIVECACHE=${USEASSOCIATIVECACHE:-false}
jq --argjson key_value ${USEASSOCIATIVECACHE} '.["useAssociativeCache"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
USEMAINEXECGENERATED=${USEMAINEXECGENERATED:-true}
jq --argjson key_value ${USEMAINEXECGENERATED} '.["useMainExecGenerated"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
ZKEVMCMPOLSAFTEREXECUTOR_DISABLED=${ZKEVMCMPOLSAFTEREXECUTOR_DISABLED:-'runtime/zkevm.commit'}
jq --arg key_value "${ZKEVMCMPOLSAFTEREXECUTOR_DISABLED}" '.["zkevmCmPolsAfterExecutor_disabled"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
ZKEVMCMPOLS_DISABLED=${ZKEVMCMPOLS_DISABLED:-'runtime/zkevm.commit'}
jq --arg key_value "${ZKEVMCMPOLS_DISABLED}" '.["zkevmCmPols_disabled"] = $key_value' '/home/ubuntu/zkevm-prover-build/config/config_prover.json' > '/home/ubuntu/zkevm-prover-build/config/temp.json' && mv '/home/ubuntu/zkevm-prover-build/config/temp.json' '/home/ubuntu/zkevm-prover-build/config/config_prover.json'
